name: .NET Core Desktop

on: push

env:
  RESOURCE-GROUP: site-vitrine-maleo
  LOCATION: westeurope
  TEMPLATE-FILE: vitrine-maleo.bicep
  SUBSCRIPTION-ID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  WEBAPP-NAME: vitrine-maleo

jobs:

  build-and-test:
    runs-on: ubuntu-latest 
    # checkout the repository
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    # Build the Wap project
    - name: Build with dotnet
      run: dotnet build ./vitrine-maleo.sln --configuration Release
    # Execute all unit tests in the solution
    - name: test with dotnet
      run: dotnet test ./vitrine-maleo.sln --configuration Release 
    # publish with dotnet
    - name : dotnet publish
      run: dotnet publish ./vitrine-maleo.csproj --configuration Release --output ./vitrine-maleo.sln.publish

    # upload the published website code artifacts
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ./vitrine-maleo.sln.publish
    
    # upload the bicep template as artifacts for next job
    - name: Upload Bicep template
      uses: actions/upload-artifact@v3
      with:
        name: vitrine-maleo.bicep
        path: ./vitrine-maleo.bicep
        artifact-path: vitrine-maleo.bicep
        type: bicep

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environments:
      name: "Development"
    steps:
    #Download the publish files created in previous job
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app
        path: .net-app

    #Download the bicep templates from previous job
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: bicep-template
        path: bicep-template
    
    #Login in your azure subscription using a service principal (credentials stored as GitHub Secret in repo)
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy Azure WebApp using Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
        resourceGroupName: ${{ env.RESOURCE-GROUP }}
        template: ./vitrine-maleo.bicep
        parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
        failOnStdErr: false   
    
    # Publish website to Azure App Service (WebApp)
    - name: Publish Website to WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.WEBAPP-NAME  }}
        package: .net-app
    
  